version: "3.5"

services:
  postgres:
    image: postgres:bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  frontend:
    image: node:lts-bullseye
    container_name: frontend
    restart: always
    working_dir: /app
    # command: bash -c 'yarn && yarn build && yarn dev'
    command: bash -c 'yarn && yarn build && yarn start'
    env_file:
      - .env
    volumes:
      - ./frontend:/app

  backend:
    image: node:lts-bullseye
    container_name: backend
    restart: always
    working_dir: /app
    # command: bash -c "yarn && yarn db:gen && yarn db:deploy && yarn build && yarn start:dev"
    command: bash -c "yarn && yarn db:gen && yarn db:deploy && yarn build && yarn start:prod"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:bullseye
    container_name: nginx
    restart: always
    ports:
      - 0.0.0.0:80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
