version: "3.5"

services:
  postgres:
    image: postgres:bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  frontend:
    image: frontend
    container_name: frontend
    build: frontend
    restart: always
    env_file:
      - .env

  backend:
    image: backend
    container_name: backend
    build: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres


  nginx:
    image: nginx:bullseye
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
