"use client";
import Button from "@/components/Button";
import { Lock } from "lucide-react";
import { useEffect, useState } from "react";
import AuthCode from "react-auth-code-input";

export default function Page() {
  const [code, setCode] = useState("");

  const handelSubmition = () => {
    console.log(code);
  };
  return (
    <div className="">
      <div className="py-8">
        <div className="text-center mb-8">
          <div className="flex justify-center mb-6">
            <Lock size={75} strokeWidth={1} />
          </div>
          <h1 className="font-semibold text-lg mb-2">
            Enter you verification code
          </h1>
          <p className="text-xs text-dark-semi-light">
            Please enter a code generated by your authenticator application in
            the field below.
          </p>
        </div>

        <AuthCode
          onChange={setCode}
          allowedCharacters="numeric"
          autoFocus
          containerClassName="flex gap-8"
          inputClassName="w-6 py-2 text-center placeholder:text-gray-400 border border-dark-semi-light block w-full bg-dark-semi-dim focus:outline-none"
        />
      </div>
      <div className="flex gap-2 justify-end">
        <Button variant="secondary">Cancel</Button>
        <Button
          className="w-full"
          onClick={handelSubmition}
        >{`Let's Go`}</Button>
      </div>
    </div>
  );
}
